# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e8b5d4a115ebbbb04ed28391e9673e3b867ec9e7a4b6ae881f6535191ac96f209594cc4714d6c48c00a755692eb4a5055e22f06fc7de0b784e4c1f0b9b5ff7

test:
  secret_key_base: 1e53fc3efd9c3d51369fc4c357ef4a3b9242db8bfccee428b6fb34deebdad7c72fffd42537cb08a1d038c3cabcdebb50ccdc7aef01736e383a9ca2c08d54c6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
